// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4yNNMGJ898bfZcD2jvlMS8PapCCJ37s',
    appId: '1:744898889581:web:1c0d811f4ca755045d3c64',
    messagingSenderId: '744898889581',
    projectId: 'xyz-project-ec7a6',
    authDomain: 'xyz-project-ec7a6.firebaseapp.com',
    storageBucket: 'xyz-project-ec7a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfn7fC_-MJ_ojXA2HCqXA3zQnUb4LGF8',
    appId: '1:744898889581:android:ffbdc39d525e71915d3c64',
    messagingSenderId: '744898889581',
    projectId: 'xyz-project-ec7a6',
    storageBucket: 'xyz-project-ec7a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKGH0xrwBNDBSSuIt1TxnmRrDJcIQiG-A',
    appId: '1:744898889581:ios:9d7f6c949e75727e5d3c64',
    messagingSenderId: '744898889581',
    projectId: 'xyz-project-ec7a6',
    storageBucket: 'xyz-project-ec7a6.appspot.com',
    iosClientId: '744898889581-h3reegpadukabhlibj4s9gmc97t7vk8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.xyzStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKGH0xrwBNDBSSuIt1TxnmRrDJcIQiG-A',
    appId: '1:744898889581:ios:9d7f6c949e75727e5d3c64',
    messagingSenderId: '744898889581',
    projectId: 'xyz-project-ec7a6',
    storageBucket: 'xyz-project-ec7a6.appspot.com',
    iosClientId: '744898889581-h3reegpadukabhlibj4s9gmc97t7vk8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.xyzStore',
  );
}
